export interface Profile {
  id: string
  name: string
  motto: string | null
  avatar_url: string | null
  streak: number
  avg_flow_time: number
  is_premium: boolean
  google_synced: boolean
  apple_synced: boolean
  language: string
  theme: string
  created_at: string
}

export interface ApiResponse<T = unknown> {
  success: boolean
  data?: T
  error?: string
}

// Calendar Event Analysis Model
export interface EventAnalysis {
  aiCategory: string; // Event category (e.g. Academic, Work, Rest, Social, Health)
  cognitiveLoadScore: number; // Cognitive load score represented as an integer from 1 - 5
  reasoning: string; // The AI's reasoning for assigning the specific category and score
}

// User Lifestyle Metrics Input Model (Backend -> AI)
export interface UserLifestyleMetrics {
  sleepDebtHours: number; // Accumulated sleep debt in hours (default: 0.0)
  snsUsageSpikeRatio: number; // Ratio of sudden increase in SNS usage compared to normal (default: 0.0)
  scheduleDensityRatio: number; // Ratio of fixed schedules during the day (default: 0.0)
  cognitiveScores: number[]; // List of cognitive load scores for today's scheduled events
}

// Burnout and Stress Analysis Result Model (AI -> Backend)
export interface BurnoutMetricsResult {
  predictedStressIndex: number; // Estimated stress index simulated using multi-dimensional data
  burnoutRiskScore: number; // Final burnout risk score ranging from 0 to 100
  riskLevel: 'Low' | 'Moderate' | 'High'; // Burnout risk level
  coachMessage: string; // Customized coaching message in a friendly tone generated by the AI
}
