# -*- coding: utf-8 -*-
"""calendar_parser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1my-9cZaGwFfWEaS7oXj7N-8aV2S_tpn0
"""

!pip install -q -U google-genai pydantic

import os
from google.colab import userdata
import google.generativeai as genai
from google.generativeai import types
from pydantic import BaseModel, Field
from google.genai import types
from google.genai import client

import time

# Configure the Gemini API key
os.environ["GEMINI_API_KEY"] = userdata.get('GEMINI_API_KEY')

# The client automatically looks for the GEMINI_API_KEY environment variable
ai = client.Client()

# Define strict data contract structure
class EventAnalysis(BaseModel):
    aiCategory: str = Field(description="Must be one of Academic, Work, Rest, Social, Health")
    cognitiveLoadScore: int = Field(description="Int from 1 (pure relaxation) to 5 (extreme mental exhaustion)")
    reasoning: str = Field(description="A brief 1-sentence explanation in Korean explaining the score")

def parse_schedule_text(title: str, user_personality: str, start_time: str = "", description: str = "") -> EventAnalysis:
    """
    Analyzes a calendar event text and returns a structured JSON object matching EventAnalysis.
    """
    system_instruction = """
    You are a professional well-being routine analysis AI. Your job is to analyze calendar event titles and descriptions to assess their mental toll.
    Categorize the event into 'Academic', 'Work', 'Rest', 'Social', or 'Health'.
    Assign a cognitiveLoadScore from 1 to 5.

    CRITICAL RULES FOR GRADING:
    - All official university exams, presentations, and interviews should be graded as 4 or 5.
    - Routine homework, club meetings, and part-time jobs should default to 3.
    - Any demanding activity (Academic, Work) occurring during late-night hours (12 AM - 5 AM) shifts the cognitive_load_score up by +1
    - Casual hangouts are 2, but late-night drinking sessions should be 3 due to physical fatigue.
    - Active recovery (gym, running) is 'Health' (score 2). Passive recovery (sleeping, watching TV) is 'Rest' (score 1).

    [Rules by MBTI type]
    - If the user is 'introvert', set the cognitive load score in the social category to +1 points higher than usual. (Interactions with many people consume energy.)
    - If the user is 'extrovert', set the Social category score as -1 points lower ONLY if it is a casual gathering with friends.
    If it is a mandatory (필참) corporate/club event, do NOT subtract points, as mandatory events cause standard fatigue for everyone.

    Examples:
    - Input: "알고리즘 기말고사 대비 밤샘 공부", Time: "23:30" -> {"aiCategory": "Academic", "cognitiveLoadScore": 5, "reasoning": "시험 대비 밤샘 공부는 극심한 정신적 피로를 유발합니다."}
    - Input: "친구들과 치맥 저녁 약속" -> {"aiCategory": "Social", "cognitiveLoadScore": 2, "reasoning": "사교 활동은 약간의 에너지를 쓰지만 리프레시에 도움이 됩니다."}
    - Input: "영화 보기" -> {"aiCategory": "Rest", "cognitiveLoadScore": 1, "reasoning": "온전한 휴식 취하기는 인지적 부하가 거의 없습니다."}
    - Input: "회식" -> {"aiCategory": "Social", "cognitiveLoadScore": 3, "reasoning": "사교 활동은 약간의 에너지를 쓰고 늦게까지 이여질 가능성이 높습니다."}
    """

    clean_time = start_time.strip()
    if len(clean_time) < 16:
        # If the time is missing or too short, default to a standard daytime slot
        clean_time = "2026-06-27T12:00:00+09:00"

    prompt = (f"Analyze this schedule slot:\n"
        f"Title: '{title}'\n"
        f"Time: '{clean_time}'\n"
        f"User Personality: '{user_personality}'\n"
        f"Description: '{description}'"
    )
    max_retries = 3
    for attempt in range(max_retries):
        try:
            response = ai.models.generate_content(
                model='gemini-2.5-flash', # make sure the model is VALID
                contents=prompt,
                config=types.GenerateContentConfig(
                    system_instruction=system_instruction,
                    response_mime_type="application/json",
                    response_schema=EventAnalysis,
                    temperature=0.1,
                ),
            )
            return EventAnalysis.model_validate_json(response.text)
        except Exception as e:
            # retry
            if attempt < max_retries - 1:
                print(f"\n Retrying {attempt+1}th time due to Google server busy (2s wait)")
                time.sleep(2)
                continue
            else:
                # raise error after 3 attempts yet fail
                raise e

# Run local test suite
if __name__ == "__main__":
    print("Running Prompt 1 Local Test with SDK...")

    test_cases = [
        {
            "title": "팀 프로젝트 회의",
            "user_personality": "introvert"
        },
        {
            "title": "알고리즘 과제 제출",
            "user_personality": "introvert",
            "start_time": "2026-06-27T20:30:00+09:00",
            "description": "기한 넘기면 감점"
        },
        {
            "title": "동아리 뒤풀이 술자리",
            "user_personality": "introvert", # Will get higher stress
            "start_time": "2026-06-27T19:00:00+09:00", # Evening
            "description": "필참"
        },
        {
            "title": "동아리 뒤풀이 술자리",
            "user_personality": "extrovert",
            "start_time": "2026-06-27T19:00:00+09:00",
            "description": "필참이라고 함"
        },
        {
            "title": "넷플릭스 보기",
            "user_personality": "extrovert",
            "start_time": "2026-06-27T11:00:00+09:00",
        }
    ]
    """
    Completed testing with the following cases:
        "팀 프로젝트 회의","수업 텀 프로젝트 회의", "헬스장 운동", "알바", "건강 검진",
        "안과 예약", "등산", "면접","TOEIC 시험","콘서트 가기", "shopping","grocery shopping",
        "시험 대비 밤샘 공부","9시까지 야근"
    """

    for case in test_cases:
        try:
            current_title = case["title"]
            current_personality = case.get("user_personality", "introvert")
            current_time = case.get("start_time", "2026-06-27T12:00:00+09:00")
            current_desc = case.get("description", "") # Safe fallback

            result = parse_schedule_text(
                title=current_title,
                user_personality=current_personality,
                start_time=current_time,
                description=current_desc
            )

            # Cleaner human-readable log output using slice [:16]
            print(f"\n[Input]: {current_title} ({current_personality} at {current_time[:16]})")
            print(f" -> Category: {result.aiCategory}")
            print(f" -> Cognitive Load Score: {result.cognitiveLoadScore}")
            print(f" -> Reasoning: {result.reasoning}")
        except Exception as e:
            print(f"\nError parsing case '{case}': {e}")